FROM ubuntu:focal

MAINTAINER Steffen Fuchs "fuchs@kobold.com"

RUN apt-get update &&  apt-get install  -y 
RUN apt-get install -y gcc  
RUN apt-get install -y build-essential
RUN apt-get install -y cmake
RUN cmake --version
