FROM ubuntu:latest

MAINTAINER Steffen Fuchs "fuchs@kobold.com"

RUN apt-get update &&  apt-get install  -y 
RUN curl software-dl.ti.com/codegen/esd/cgt_public_sw/TMS470/20.2.0.LTS/ti_cgt_tms470_20.2.0.LTS_linux_installer_x86.bin -O   
