name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Cppcheck
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:cppcheck"
          push: true
          tags: mrnoies/cppcheck:latest
      -
        name: Build and push Cmake
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:cmake-gcc"
          push: true
          tags: mrnoies/cmake-gcc:latest
      -
        name: Build and push Ceedling
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:ceedling"
          push: true
          tags: mrnoies/ceedling:latest
